# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAe4Y_oN7boHlqph4UwYgSo5wWFwFmSh
"""

import streamlit as st
import tensorflow as tf

@st.cache_resource
def load_model():
  model=tf.keras.models.load_model('plant_classifier.hdf5')
  return model
model=load_model()
st.write("""
# Image classification model
-Muyrong, Caberte
"""
)
file=st.file_uploader("Choose a photo from computer to classify",type=["jpg","png"])

import cv2
from PIL import Image,ImageOps
import numpy as np
def import_and_predict(image_data,model):
    size=(64,64)
    image=ImageOps.fit(image_data,size)
    img=np.asarray(image)
    img_reshape=img[np.newaxis,...]
    prediction=model.predict(img_reshape)
    return prediction
if file is None:
    st.text("Please upload an image file")
else:
    image=Image.open(file)
    st.image(image,use_column_width=True)
    prediction=import_and_predict(image,model)
    class_names=[''Dinosaur', 'Flag', 'Airplane', 'Puppy']
    string="OUTPUT : "+class_names[np.argmax(prediction)]
    st.success(string)

